# Generated by Django 4.1 on 2022-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombers', models.CharField(max_length=10, verbose_name='Номер проекта')),
                ('Date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('NameProg', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Status', models.CharField(max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Таблица регистрации',
            },
        ),
    ]
