# Generated by Django 4.1 on 2022-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=10, verbose_name='Номер проекта')),
                ('NameProg', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Date_born', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('Responsible', models.CharField(max_length=100, verbose_name='Отвественный')),
                ('Customer_company', models.CharField(max_length=100, verbose_name='Организация заказчик')),
                ('Adres_obj', models.CharField(max_length=300, verbose_name='Адрес объекта')),
                ('Status', models.CharField(max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Таблица регистрации',
            },
        ),
    ]
