# Generated by Django 4.1 on 2022-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Customer_company',
            field=models.IntegerField(max_length=10, verbose_name='Организация заказчик ИНН'),
        ),
    ]
