# Generated by Django 4.1 on 2023-11-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Status',
            field=models.CharField(choices=[('1', 'создан'), ('2', 'в работе'), ('3', 'согласован'), ('4', 'завершен')], default='создан', max_length=30, verbose_name='Статус'),
        ),
    ]
