# Generated by Django 4.1 on 2022-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_reg_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Adres_obj',
            field=models.TextField(verbose_name='Адрес объекта'),
        ),
    ]
