# Generated by Django 4.1 on 2022-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_alter_reg_adres_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Status',
            field=models.CharField(default='создан', max_length=15, verbose_name='Статус'),
        ),
    ]
