# Generated by Django 4.1 on 2022-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_reg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='reg',
            name='Status',
            field=models.CharField(choices=[('1', 'создан'), ('2', 'зарегистрирован'), ('3', 'согласован'), ('4', 'завершен')], default='создан', max_length=1, verbose_name='Статус'),
        ),
    ]
