# Generated by Django 4.1 on 2022-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_stat_alter_reg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Status',
            field=models.CharField(choices=[('1', 'создан'), ('2', 'зарегистрирован'), ('3', 'согласован'), ('4', 'завершен')], default='создан', max_length=30, verbose_name='Статус'),
        ),
    ]
