# Generated by Django 4.1.1 on 2022-09-06 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SolVed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomZak', models.IntegerField(max_length=4, verbose_name='Номер заказа')),
                ('NameProg', models.CharField(db_column='NameProg', max_length=30, verbose_name='Наименование проекта')),
                ('Date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('Responsible', models.CharField(max_length=40, verbose_name='Отвественный')),
                ('PromPlosh', models.CharField(choices=[('Питон кама', 'Питон кама'), ('Солярис', 'Солярис')], max_length=30, verbose_name='Производственная площадка')),
                ('Status', models.CharField(choices=[('создан', 'создан'), ('в работе', 'в работе'), ('на упаковке', 'на упаковке'), ('отгружен', 'отгружен'), ('завершён', 'завершён')], default='создан', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Таблица Заказов',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
